### ISSUE TITLE
Calendar doesn't go into the future - Feature request

### ISSUE THREAD

**Issue by Theunodb** [dan-iel-lee/calendar_widget#1]
Is it possible to view dates that are in the future. Currently we can only see the current month, and dates that are in the past.

**Comment by dan-iel-lee** [comment]
Yeah that's a good idea, I didn't think of that because my specific use case didn't need that.
I'll get that added within the next few days.

**Comment by dan-iel-lee** [comment]
I've added the feature! Update to version 0.1.0 to use it
